apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terrascope
  namespace: terrascope
spec:
  rules:
    - host: terrascope.cloud
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: terrascope-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: terrascope-frontend
                port:
                  number: 80
