apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: terrascope-gateway
  namespace: terrascope
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "terrascope.cloud"
      allowedRoutes:
        namespaces:
          from: Same
